### ISSUE TITLE
Togliere il riferimento a vagrant-lamp

### ISSUE THREAD

**Issue by lorello** [softecspa/vagrant-init#2]
Inizialmente avevamo fatto quella sola macchina con vagrant, adesso che sono 4 o 5 e stanno crescendo rapidamente conviene evitare di clonare il repository di quella e lasciare questo step allo sviluppatore.

**Comment by uaiz** [comment]
tolti i riferimenti a vagrant-lamp

**Comment by lorello** [comment]
pero' non vedo il commit :)

2015-02-16 16:43 GMT+01:00 uaiz notifications@github.com:

> tolti i riferimenti a vagrant-lamp
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/softecspa/vagrant-init/issues/2#issuecomment-74527334
> .

## 

Lorenzo Salvadorini
Systems & Network Manager
_Tel_ +39 0574 5877 132

Questa e-mail e tutti i suoi allegati sono da intendersi confidenziali e
riservati. Se non siete l'effettivo destinatario o avete ricevuto il
messaggio per errore siete pregati di cancellarlo dal vostro sistema e di
avvisare il mittente. Siete altresì informati che qualsiasi utilizzo,
copia, comunicazione, divulgazione dei contenuti del messaggio e dei suoi
allegati, a qualunque titolo, è vietata dalla legge.

This email and any attachments are privileged and confidential. If you are
not the intended recipient please delete it from your system and notify the
sender. You should not copy it or use it for any purpose nor disclose or
distribute its contents to any other person. You should as well be aware
that any use, copy, disclosure and distribution of the contents and the
possible attachments of this email, at any title, is forbidden by the Law.
